<html>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><span style="height:0pt; text-align:left; display:block; position:absolute; z-index:1;"><img src="image/logo.jpg" width="120px"></span><strong><span style="font-family:'Times New Roman';">PEMERINTAH</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">KOTA</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">JAMBI</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">KECAMATAN JAMBI TIMUR</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:18pt;"><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">K E</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">L U R A H A N</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">S U L A N J A N A</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:11pt;"><strong><span style="font-family:'Times New Roman';">Jalan Orang</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kayo</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Hitam</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">No. 09</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kode Pos 36144</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><strong><span style="font-family:'Times New Roman';">J A M B I &ndash; T</span></strong><strong><span style="font-family:'Times New Roman';">LP &amp; FAKS</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">(0741 )</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">33035</span></strong></p>
<div style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;border-bottom:solid windowtext 3.0pt;padding:0cm 0cm 1.0pt 0cm;'>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;border:none;padding:0cm;'><strong>&nbsp;</strong></p>
</div>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;'><span style='font-size:21px;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:center;'><strong><u><span style='font-size:21px;font-family:"Arial",sans-serif;'>SURAT&nbsp;</span></u></strong><strong><u><span style='font-size:21px;font-family:"Arial",sans-serif;'>KETERANGAN TIDAK MAMPU<br>&nbsp;</span></u></strong><strong><span style='font-family:"Arial",sans-serif;'>Nomor &nbsp;:</span></strong><span style='font-family:"Arial",sans-serif;'>&nbsp;470/&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp;</span><span style='font-family:"Arial",sans-serif;'>/ SLJ/ 2021</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:center;text-indent:2.0cm;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;text-indent:2.0cm;'><span style='font-family:"Arial",sans-serif;'>Yang bertanda tangan di bawah ini &nbsp;Kepala &nbsp;Kelurahan &nbsp;Sulanjana Kecamatan&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Jambi &nbsp;Timur &nbsp; menerangkan &nbsp; bahwa :</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>N &nbsp;a &nbsp;m &nbsp;a &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span> : &nbsp; &nbsp;&nbsp;<span style='font-family:"Arial",sans-serif;'><?=$details->nama?></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>Tempat/Tanggal Lahir&nbsp;&nbsp;&nbsp;: &nbsp;&nbsp;&nbsp; </span><span style='font-family:"Arial",sans-serif;'></span><span style='font-family:"Arial",sans-serif;'><?=$details->tempat_lahir?>, <?=tgl_indo($details->tanggal_lahir)?>&nbsp; &nbsp; &nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>NIK&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;: &nbsp; &nbsp;&nbsp;<?=$details->nik?></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>A &nbsp;g &nbsp;a &nbsp;m &nbsp;a &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp;&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp;&nbsp;</span><span style='font-family:"Arial",sans-serif;'><?=$details->agama?></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>Jenis Kelamin &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;:&nbsp; &nbsp;&nbsp; <?=$details->jenis_kelamin?></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:201.3pt;text-align:justify;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>Pekerjaan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; : &nbsp;&nbsp;&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp;<?=$details->pekerjaan?></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:177.3pt;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-family:"Arial",sans-serif;'>A l a m a t  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp;</span><span style='font-family:"Arial",sans-serif;'> :</span><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&nbsp;&nbsp;&nbsp;<?=$details->alamat?> </p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:177.3pt;text-indent:-141.3pt;'><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;text-indent:36.0pt;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Berdasarkan surat pengantar ketua RT.</span><span style='font-family:"Arial",sans-serif;'><?=$details->rt_pengantar?>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Nomor:</span><span style='font-family:"Arial",sans-serif;'>&nbsp;<?=$details->nomor_surat_pengantar?></span><span style='font-family:"Arial",sans-serif;'>&nbsp;tanggal</span><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><span style='font-family:"Arial",sans-serif;'><?=tgl_indo($details->tanggal_surat_pengantar)?>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Nama tersebut diatas adalah benar warga RT.&nbsp;</span><span style='font-family:"Arial",sans-serif;'><?=$details->rt_pengantar?>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Kelurahan Sulanjana Kecamatan Jambi Timur Kota Jambi, nama tersebut diatas Tergolong <strong>Warga Kurang Mampu</strong></span><span style='font-family:"Arial",sans-serif;'>.</span><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Berikut ini tercantum daftar keluarga yang bersangkutan.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;text-indent:36.0pt;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Surat keterangan ini di berikan kepada yang bersangkutan untuk&nbsp;</span><span style='font-family:"Arial",sans-serif;'>persyaratan&nbsp;</span><span style='font-family:"Arial",sans-serif;'>&ldquo;<strong><?=$details->keperluan?>&rdquo;.</strong></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Demikianlah surat keterangan ini &nbsp;diberikan &nbsp; untuk &nbsp; dapat dipergunakan</span><span style='font-family:"Arial",sans-serif;'>&nbsp;sebagaimana mestin</span><span style='font-family:"Arial",sans-serif;'>ya.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:216.0pt;'><span style='font-family:"Arial",sans-serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:216.0pt;'><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-indent:2.0cm;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jambi, <?=tgl_indo($details->tanggal_surat_pengantar)?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="font-size:15px;">KEPALA KELURAHAN SULANJANA&nbsp;&nbsp;</span></strong><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;line-height:150%;'><span style="font-size:15px;line-height:150%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:15px;line-height:150%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;line-height:150%;'><span style="font-size:15px;line-height:150%;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;line-height:150%;'><span style="font-size:15px;line-height:150%;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong><u>HUSIN,SE</u></strong></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span>&nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Penata</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;NIP. 19731228 200701 1 008</p>
</html>