<html>


<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><span style="height:0pt; text-align:left; display:block; position:absolute; z-index:1;"><img src="image/logo.jpg" width="120px"></span><strong><span style="font-family:'Times New Roman';">PEMERINTAH</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">KOTA</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">JAMBI</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">KECAMATAN JAMBI TIMUR</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:18pt;"><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">K E</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">L U R A H A N</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">S U L A N J A N A</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:11pt;"><strong><span style="font-family:'Times New Roman';">Jalan Orang</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kayo</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Hitam</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">No. 09</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kode Pos 36144</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><strong><span style="font-family:'Times New Roman';">J A M B I &ndash; T</span></strong><strong><span style="font-family:'Times New Roman';">LP &amp; FAKS</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">(0741 )</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">33035</span></strong></p>
<div style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;border-bottom:double windowtext 2.25pt;padding:0cm 0cm 1.0pt 0cm;'>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;padding:0cm;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
</div>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;'><strong><span style="font-size:21px;"><span style="text-decoration:none;">&nbsp;</span></span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;'><strong><u><span style="font-size:21px;">SURAT &nbsp;KETERANGAN</span></u></strong><strong><u><span style="font-size:21px;">&nbsp;</span></u></strong><strong><u><span style="font-size:21px;">&nbsp;</span></u></strong><strong><u><span style="font-size:21px;">USAHA</span></u></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;'><span style="font-size:21px;">&nbsp; NOMOR : <?=$details->nomor_surat?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:center;'><br></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Yang bertanda tangan di bawah ini Kepala Kelurahan Sulanjana dengan ini, <br> menerangkan bahwa: &nbsp;</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:212.65pt;text-indent:-212.65pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Nama &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp; &nbsp;<?=$details->nama?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:248.1pt;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;NIK &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; &nbsp;<?=$details->nik?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:246.1pt;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Tempat tgl lahir &nbsp; &nbsp;    &nbsp;&nbsp;    &nbsp;&nbsp;     &nbsp; &nbsp; : &nbsp; &nbsp;<?=$details->tempat?>, <?=tgl_indo($details->tgl_lahir)?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Jenis Kelamin &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; &nbsp;<?=$details->jenis_kelamin?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Pekerjaan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp; &nbsp;<?=$details->pekerjaan?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kewargaan Negara &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; &nbsp;<?=$details->kewarganegaraan?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Golongan Darah &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; &nbsp;<?=$details->golongan_darah?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Status Perkawinan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp; &nbsp;<?=$details->status_perkawinan?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A g a m a &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp; &nbsp;<?=$details->agama?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Alamat Tempat Tinggal &nbsp;: &nbsp; &nbsp;<?=$details->alamat_tempat_tinggal?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:198.0pt;text-align:justify;text-indent:-198.0pt;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Berdasarkan surat Pengantar Ketua RT. <?=$details->rt_pengantar?> Tanggal <?=tgl_indo($details->tanggal_surat_pengantar)?> bahwa nama tersebut diatas benar Mempunyai Usaha di &nbsp;RT. <?=$details->rt?> &nbsp;Kelurahan Sulanjana Kecamatan Jambi Timur Kota Jambi, menerangkan bahwa yang bersangkutan memang benar mempunyai usaha <?=$details->usaha?> .</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Surat keterangan ini diberikan kepada yang &nbsp;bersangkutan &nbsp;untuk &nbsp;keperluan &nbsp;persyaratan <strong><?=$details->keperluan?></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Demikianlah surat keterangan ini kami buat untuk dapat dipergunakan sebagaimana mestinya.&nbsp;</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;'>&nbsp; &nbsp; . &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-align:justify;'>&nbsp;</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-bottom:6.0pt;text-indent:2.0cm;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Jambi, &nbsp; &nbsp; &nbsp;<?=tgl_indo($details->tanggal_surat)?></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong><strong>&nbsp; &nbsp;</strong><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  KEPALA KELURAHAN SULANJANA</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<u>HUSIN.SE</u></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:108.0pt;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Penata&nbsp;</p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;NIP. 19731228 &nbsp;200701 1 008</p>
<!-- <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</p> -->
</html>