<html>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><span style="height:0pt; text-align:left; display:block; position:absolute; z-index:1;"><img src="image/logo.jpg" width="120px"></span><strong><span style="font-family:'Times New Roman';">PEMERINTAH</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">KOTA</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">JAMBI</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:14pt;"><strong><span style="font-family:'Times New Roman';">KECAMATAN JAMBI TIMUR</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:18pt;"><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">K E</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">L U R A H A N</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">S U L A N J A N A</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:11pt;"><strong><span style="font-family:'Times New Roman';">Jalan Orang</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kayo</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Hitam</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">No. 09</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">Kode Pos 36144</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><strong><span style="font-family:'Times New Roman';">J A M B I &ndash; T</span></strong><strong><span style="font-family:'Times New Roman';">LP &amp; FAKS</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">(0741 )</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">33035</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; border-bottom:2.25pt double #000000; padding-bottom:1pt; font-size:12pt;"><span style="width:216pt; display:inline-block;">&nbsp;</span><span style="width:128pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><strong><u><span style="font-family:'Times New Roman';">SURAT</span></u></strong><strong><u><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></u></strong><strong><u><span style="font-family:'Times New Roman';">KETERANGAN</span></u></strong><strong><u><span style="font-family:'Times New Roman';">&nbsp;DOMISILI</span></u></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;"><span style="font-family:'Times New Roman';">NOMOR :</span><span style="font-family:'Times New Roman';">&nbsp;&nbsp;</span><span style="font-family:'Times New Roman';"><?= $details->nomor_surat?></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="width:48pt; display:inline-block;">&nbsp;</span><span style="width:24pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Yang bertanda tangan di bawah ini Kepala Kelurahan Sulanjana</span><span style="font-family:'Times New Roman';">&nbsp;Kecamatan</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Jambi Timur&nbsp;</span><span style="font-family:'Times New Roman';">dengan ini , menerangkan bahwa:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong></p>
<p style="margin-top:0pt; margin-bottom:6pt; text-align:justify; font-size:12pt;"><span style="width:36pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Nama</span><span style="width:49.35pt; display:inline-block;">&nbsp;</span><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp;&nbsp;</span></strong><span style="width:12pt; display:inline-block;">&nbsp;</span><span style="width:36pt; display:inline-block;">&nbsp;</span><span style="width:36pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->nama?></span></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Tempat tgl lahir</span><span style="width:0.69pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:83.9pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->tempat_lahir?>, <?=tgl_indo($details->tanggal_lahir)?></span></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">NIK</span><span style="width:56.67pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:83.9pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->nik?></span></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Jenis Kelamin</span><span style="width:9.68pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:83.9pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span></strong><span style="font-family:'Times New Roman';"><?=$details->jenis_kelamin?></span></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Agama</span><span style="width:43.35pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:83.9pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->agama?></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Kewarganegaraan</span><span style="width:75.29pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->kewarganegaraan?></span></p>
<p style="margin-top:0pt; margin-left:197.9pt; margin-bottom:6pt; text-indent:-197.9pt; text-align:justify; font-size:12pt;"><span style="width:36pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Pekerjaan</span><span style="width:30.69pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:83.9pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:18.1pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->pekerjaan?></span></p>
<p style="margin-top:0pt; margin-left:226.8pt; margin-bottom:6pt; text-indent:-216pt; text-align:justify; font-size:12pt;"><span style="width:25.2pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Alamat</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="width:93.68pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">:</span><span style="width:7.47pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';"><?=$details->alamat?></p>
<p style="margin-top:0pt; margin-left:226.8pt; margin-bottom:6pt; text-indent:-226.8pt; text-align:justify; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:6pt; text-align:justify; line-height:150%; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Berdasarkan surat pengantar Ketua RT. <?=$details->rt_pengantar?> Nomor : <?=$details->nomor_surat_pengantar?> Tanggal <?=tgl_indo($details->tanggal_surat_pengantar)?>, </span><span style="font-family:'Times New Roman';">Bahwa benar nama&nbsp;</span><span style="font-family:'Times New Roman';">yang tersebut diatas memang benar merupakan warga RT.<?=$details->rt_pengantar?>&nbsp;</span><span style="font-family:'Times New Roman';">Kel.Sulanjana Kecamatan Jambi Timur.</span></p>
<p style="margin-top:0pt; margin-bottom:6pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="width:36pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">Surat&nbsp;</span><span style="font-family:'Times New Roman';">Surat Keterangan ini digunakan untuk keperluan </span><span style="font-family:'Times New Roman';">&nbsp;<?=$details->keperluan?>.</span></p>
<p style="margin-top:0pt; margin-bottom:6pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-family:'Times New Roman';">Demikianlah Surat Keterangan ini agar dapat dipergunakan sebagai mestinya.</span></p>
<p style="margin-top:0pt; margin-bottom:6pt; text-indent:56.7pt; font-size:12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><span style="width:0.3pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="width:126pt; text-indent:0pt; display:inline-block;">&nbsp;</span><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><span style="font-family:'Times New Roman';">Jambi</span><span style="font-family:'Times New Roman';">, <?=tgl_indo($details->tanggal_surat)?></span></p>
<p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:12pt;"><span style="width:72pt; display:inline-block;">&nbsp;</span><span style="width:110pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><strong><span style="font-family:'Times New Roman';">KEPALA KELURAHAN SULANJANA</span></strong></p>
<p style="margin-top:0pt; margin-left:60pt; margin-bottom:0pt; text-indent:-24pt; text-align:justify; font-size:11pt;"><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="width:4.75pt; text-indent:0pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp;</span></p>
<p style="margin-top: 0pt; margin-left: 297.7pt; margin-bottom: 0pt; text-indent: -45.7pt; text-align: left; font-size: 12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong></p>
<p style="margin-top: 0pt; margin-left: 297.7pt; margin-bottom: 0pt; text-indent: -45.7pt; text-align: left; font-size: 12pt;"><br></p>
<p style="margin-top: 0pt; margin-left: 297.7pt; margin-bottom: 0pt; text-indent: -45.7pt; text-align: left; font-size: 12pt;"><strong><span style="font-family:'Times New Roman';">&nbsp;</span></strong><strong><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><u><span style="font-family:'Times New Roman';">H U S I N.SE</span></u></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><span style="width:242pt; display:inline-block;">&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-family:'Times New Roman';">&nbsp;</span><span style="font-family:'Times New Roman';">Penata</span><span style="font-family:'Times New Roman';">&nbsp; &nbsp;&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><span style="font-family:'Times New Roman';">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:'Times New Roman';">NIP.&nbsp;</span><span style="font-family:'Times New Roman';">19731228 200701 1 008</span></p>

</html>