<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_keterangan_usaha_model extends CI_Model
{

    public $table = 'surat_keterangan_usaha';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('kewarganegaraan', $q);
	$this->db->or_like('golongan_darah', $q);
	$this->db->or_like('status_perkawinan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('rt', $q);
	$this->db->or_like('alamat_tempat_tinggal', $q);
	$this->db->or_like('rt_pengantar', $q);
	$this->db->or_like('nomor_surat_pengantar', $q);
	$this->db->or_like('tanggal_surat_pengantar', $q);
	$this->db->or_like('keperluan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('kewarganegaraan', $q);
	$this->db->or_like('golongan_darah', $q);
	$this->db->or_like('status_perkawinan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('rt', $q);
	$this->db->or_like('alamat_tempat_tinggal', $q);
	$this->db->or_like('rt_pengantar', $q);
	$this->db->or_like('nomor_surat_pengantar', $q);
	$this->db->or_like('tanggal_surat_pengantar', $q);
	$this->db->or_like('keperluan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_keterangan_usaha_model.php */
/* Location: ./application/models/Surat_keterangan_usaha_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-19 16:09:13 */
/* http://harviacode.com */